name: Migrate Postgres to Postgres


on:
  workflow_dispatch: {}

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sqlalchemy psycopg2-binary
      - name: Run migration
        env:
          SRC_DB_URL: ${{ secrets.SRC_DB_URL }}
          DST_DB_URL: ${{ secrets.DST_DB_URL }}
         run: echo "Skip migration"
   
